# Generated by Django 5.0.1 on 2024-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyweave", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="full_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
