# Generated by Django 5.0.1 on 2024-07-08 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyweave", "0003_customusermodel_alter_profile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storyweave.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                ("segment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("vote_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vote_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUserModel",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RenameField(
            model_name="story",
            old_name="created_at",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="content",
            new_name="summary",
        ),
        migrations.RemoveField(
            model_name="story",
            name="id",
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="story_id",
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="segment",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storyweave.story"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storyweave.segment"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storyweave.segment"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
